[tool.poetry]
name = "matrix-loading"
version = "0.1.0"
description = "Matrix data analysis exercise"
authors = ["wezhou <wezhou@student.42tokyo.jp>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pandas = "*"
numpy = "*"
matplotlib = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"